build: introduce golden tests (#12)
* feat: introduce debug settings screen

* build: introduce golden tests

* chore: update changelog

diff --git a/.github/workflows/build_app.yaml b/.github/workflows/build_app.yaml
--- a/.github/workflows/build_app.yaml
+++ b/.github/workflows/build_app.yaml
@@ -55,7 +55,6 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           folders: "lib, test"
-          check_unused_files: true
           pull_request_comment: true
 
       - name: Verify formatting
@@ -82,20 +81,48 @@ jobs:
         run: flutter pub get
 
       - name: Run tests
-        run: flutter test
+        run: flutter test --exclude-tags=golden --reporter=expanded
 
       - name: Publish test results
         uses: dorny/test-reporter@v1
         if: success() || failure() # run this step even if previous step failed
         with:
-          name: Test results
+          name: Tests result
+          path: reports/tests.json
+          reporter: dart-json
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+  golden_testing:
+    needs: analysis
+    runs-on: macos-11
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Install Flutter
+        uses: subosito/flutter-action@v1
+        with:
+          channel: "stable"
+
+      - name: Install dependencies
+        run: flutter pub get
+
+      - name: Run tests
+        run: flutter test --tags=golden --reporter=expanded
+
+      - name: Publish test results
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Golden Tests result
           path: reports/tests.json
           reporter: dart-json
           token: ${{ secrets.GITHUB_TOKEN }}
 
   build-apk:
     name: "build apk"
-    needs: testing
+    needs: [testing, golden_testing]
     runs-on: ubuntu-latest
 
     defaults:
@@ -126,7 +153,7 @@ jobs:
 
   build-web:
     name: "build web"
-    needs: testing
+    needs: [testing, golden_testing]
     runs-on: ubuntu-latest
 
     defaults:
