chore: update ci/cd

diff --git a/.github/workflows/static_analyze.yaml b/.github/workflows/static_analyze.yaml
--- a/.github/workflows/static_analyze.yaml
+++ b/.github/workflows/static_analyze.yaml
@@ -1,40 +1,42 @@
-name: Static analyze
+name: "Analyze package"
 
 on:
   push:
-    branches: [main]
+    branches:
+      - main
   pull_request:
-    branches: [main]
+    branches:
+      - main
 
 jobs:
   analyze:
-    name: Static analyze
-
     runs-on: ubuntu-latest
 
-    defaults:
-      run:
-        shell: bash
-
     steps:
-      - name: Checkout 🛎️
-        uses: actions/checkout@v2
+      - name: Validate semantic changelog update
+        if: ${{ github.event_name == 'pull_request' }}
+        uses: GetStream/verify-semantic-changelog-update@v1.0.0
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Install Flutter 🔧
+      - name: Install Flutter
         uses: subosito/flutter-action@v1
         with:
           channel: "stable"
 
-      - name: Install dependencies 🔧
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Install dependencies
         run: flutter pub get
 
-      - name: Run dependency validator 🔍
+      - name: Run dependency validator
         run: |
-          dart pub global activate dependency_validator
-          dart pub global run dependency_validator:dependency_validator
+          flutter pub global activate dependency_validator
+          flutter pub global run dependency_validator:dependency_validator
 
-      - name: Run analyzer 🔍
-        run: flutter analyze --no-pub --fatal-warnings --fatal-infos .
+      - name: Analyze project
+        run: flutter analyze --no-pub .
 
       - name: dart-code-metrics
         uses: dart-code-checker/dart-code-metrics-action@v1
@@ -42,14 +44,11 @@ jobs:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           folders: "lib, test"
 
-      - name: Run formatter 🔍
+      - name: Verify formatting
         run: flutter format --set-exit-if-changed .
 
-  tests:
-    name: Run tests
-
-    needs: analyze
-
+  testing:
+    needs: analysis
     runs-on: ubuntu-latest
 
     defaults:
@@ -57,16 +56,25 @@ jobs:
         shell: bash
 
     steps:
-      - name: Checkout 🛎️
-        uses: actions/checkout@v2
-
-      - name: Install Flutter 🔧
+      - name: Install Flutter
         uses: subosito/flutter-action@v1
         with:
           channel: "stable"
 
-      - name: Install dependencies 🔧
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Install dependencies
         run: flutter pub get
 
-      - name: Run tests ⚙️
+      - name: Run tests
         run: flutter test
+
+      - name: Upload test results
+        uses: actions/upload-artifact@v2
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: "Test results"
+          path: reports/tests.json
+          reporter: dart-json
+          token: ${{ secrets.GITHUB_TOKEN }}
